name: Cybokhackers

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 999999999999999999

    steps:
    - name: download Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/samay826/Samay_Latest_RDp/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/samay826/Samay_Latest_RDp/main/wallpaper.png -OutFile wallpaper.bmp
        Invoke-WebRequest https://raw.githubusercontent.com/samay826/Samay_Latest_RDp/main/wallpaper.bat -OutFile wallpaper.bat
    - name: extract Ngrok File.
      run: Expand-Archive ngrok.zip
    - name: Connect to  Ngrok.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Connecting the Cybok server RDP.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.bmp D:\a\wallpaper.bmp
        copy wallpaper.bat D:\a\wallpaper.bat
    - name: SAMAY
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
    - name: Connect Ke RDP CPU 2 Core - 7GB Ram - 255 SSD.
      run: cmd /c start.bat
    - name: Cybokhackers
      run: | 
        Invoke-WebRequest https://raw.githubusercontent.com/samay826/Samay_Latest_RDp/main/loop.ps1 -OutFile loop.ps1
        ./loop.ps1
